/*
* Prompt: How many distinct terms are in the sequence generated by a^(b) for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
*
* Execute: javac Problem29.java; java Problem29; rm Problem29.class
*
* Answer: 9183
*/
import java.math.BigInteger;
import java.util.HashSet;
import java.util.Set;

public class Problem29 {
  public static void main(String[] args) {
    Set<BigInteger> distinctValues = new HashSet<BigInteger>();
    for (int a = 2; a <= 100; a++) {
      for (int b = 2; b <= 100; b++) {
        distinctValues.add(BigInteger.valueOf(a).pow(b));
      }
    }
    System.out.println(distinctValues.size());
  }
}
